disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name
  - for_where
opt_in_rules:
  - empty_count
  - sorted_first_last
  - contains_over_first_not_nil
  - first_where
  - closure_end_indentation
  - closure_spacing
line_length:
  warning: 140
  error: 200
type_body_length:
  warning: 300
file_length:
  warning: 500
excluded:
  - .build
  - DerivedData
